# Generated by Django 5.0.1 on 2024-01-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetail',
            name='amenities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
