# Generated by Django 5.0.1 on 2024-01-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_roomdetail_amenities_alter_roomdetail_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomdetail',
            old_name='type',
            new_name='room_type',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomdetail',
            name='bed_type',
            field=models.CharField(blank=True, choices=[('single_bed', 'Single Bed'), ('double_bed', 'Double Bed'), ('king_bed', 'King Bed')], max_length=30, null=True),
        ),
    ]
