# Generated by Django 5.0.1 on 2024-01-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0005_rename_type_roomdetail_room_type_roombooking_adults_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roombooking",
            name="room",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="room.room",
            ),
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image1", models.ImageField(upload_to="images/room_image")),
                ("image2", models.ImageField(upload_to="images/room_image")),
                ("image3", models.ImageField(upload_to="images/room_image")),
                ("image4", models.ImageField(upload_to="images/room_image")),
                ("image5", models.ImageField(upload_to="images/room_image")),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="room.room"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="roomdetail",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="room.roomimage",
            ),
        ),
    ]
