# Generated by Django 5.0.1 on 2024-01-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_room_booked_reservation_delete_roombooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('family', 'Family'), ('deluxe', 'Deluxe'), ('president', 'President')], max_length=50),
        ),
    ]
