# Generated by Django 5.0.1 on 2024-01-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_menucategory_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='user_review',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.RemoveField(
            model_name='menulist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='reviewandrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
        migrations.DeleteModel(
            name='MenuList',
        ),
        migrations.DeleteModel(
            name='ReviewAndRating',
        ),
    ]
