# Generated by Django 5.0.1 on 2024-01-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_alter_reservation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='booked',
            new_name='occupied',
        ),
    ]
