# Generated by Django 5.0.1 on 2024-01-28 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_rename_booked_room_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetail',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_detail', to='room.room'),
        ),
    ]
