# Generated by Django 5.0.1 on 2024-02-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0015_bookingconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingconfirmation',
            name='reservation',
        ),
        migrations.AddField(
            model_name='bookingconfirmation',
            name='reservation',
            field=models.ManyToManyField(blank=True, null=True, to='room.reservation'),
        ),
    ]
