# Generated by Django 5.0.1 on 2024-02-11 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0016_remove_bookingconfirmation_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingconfirmation',
            name='reservation',
        ),
        migrations.AddField(
            model_name='bookingconfirmation',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.reservation'),
        ),
    ]
