# Generated by Django 5.0.1 on 2024-02-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_remove_bookingconfirmation_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingconfirmation',
            name='room',
        ),
        migrations.AddField(
            model_name='bookingconfirmation',
            name='room',
            field=models.ManyToManyField(blank=True, null=True, to='room.room'),
        ),
    ]
