# Generated by Django 5.0.1 on 2024-02-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0018_remove_bookingconfirmation_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingconfirmation',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
