# Generated by Django 5.0.1 on 2024-02-13 03:24

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('theme', models.CharField(max_length=300)),
                ('event_banner', models.ImageField(upload_to='event/banner')),
                ('body', tinymce.models.HTMLField()),
                ('event_start', models.DateField(auto_now_add=True)),
                ('event_end', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
