# Generated by Django 5.0.1 on 2024-02-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hotelcontactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelcontactinfo',
            options={'verbose_name': 'Hotel Contact Information'},
        ),
        migrations.AddField(
            model_name='hotelcontactinfo',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelcontactinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelcontactinfo',
            name='x_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
