# Generated by Django 5.0.1 on 2024-02-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
