# Generated by Django 5.0.1 on 2024-02-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_testimonial_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='hotel_banner')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='hotel_banner')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='hotel_banner')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='hotel_banner')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='hotel_banner')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='hotel_banner')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='hotel_banner')),
            ],
        ),
    ]
