# Generated by Django 5.0.1 on 2024-02-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
